version: '3.8'

services:
  app:
    build: .
    container_name: regulation_prix_app_remote
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-etudiant-esp.alwaysdata.net:3306/etudiant-esp_thecircle?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: 421326_thecircle
      SPRING_DATASOURCE_PASSWORD: esppasswd
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_CHARACTERENCODING: utf8mb4
      SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_CHARSET: UTF-8
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      JAVA_OPTS: -Xmx512m -Xms256m -XX:+UseG1GC
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
